<?php

require_once dirname(__FILE__) . '\..\..\..\newPct\dlm\search.php';
require_once dirname(__FILE__) . '\..\..\..\plugin.php';

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-06-08 at 03:45:35.
 */
class SynoDLMSearchNewPctTest extends PHPUnit_Framework_TestCase {

    /**
     * @var SynoDLMSearchNewPct
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new SynoDLMSearchNewPct;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers SynoDLMSearchNewPct::parse
     */
    public function testParse() {
        $plugin = new plugin();
        $curl = curl_init();
        $query = "diablo";
        $this->object->prepare($curl, $query);
        $data = curl_exec($curl);
        $this->assertGreaterThan(0, $this->object->parse($plugin, $data), "No hay resultados");
    }

}
