<?php
namespace SynDsEsTorrent\tests\modules\divxtotal\dlm;
require_once dirname(__FILE__) . '\..\..\..\..\..\vendor\autoload.php';
require_once dirname(__FILE__) . '\..\..\..\..\..\SynDsEsTorrent\modules\divxtotal\dlm\search.php';
/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-09-13 at 04:16:04.
 */
class SynoDLMSearchDivxTotalTest extends \SynDsEsTorrent\utils\baseDlmTest {

    public function setUp(){
        parent::setObject(new \SynoDLMSearchDivxTotal);
    }
    /**
     * @covers SynoDLMSearchNewPct::parse
     */
    public function testParse() {
       parent::parse();
    }

}
