<?php

//namespace SynDsEsTorrent\modules\divxtotal\dlm;
require_once '..\utils\Plugin.php';
require_once '..\modules\divxtotal\dlm\SynoDLMSearchDivxTotal.php';

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-07-25 at 18:23:22.
 */
class SynoDLMSearchDivxTotalTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var SynoDLMSearchDivxTotal
     */
    protected $search_provider;

    protected function setUp()
    {
        $this->search_provider = new SynoDLMSearchDivxTotal;
    }

    /**
     * @covers SynDsEsTorrent\modules\divxtotal\dlm\SynoDLMSearchDivxTotal::parse
     */
    public function testParse()
    {
        $plugin = new SynDsEsTorrent\utils\plugin();
        $curl = curl_init();
        $query = "ú";
        $this->search_provider->prepare($curl, $query);
        $data = curl_exec($curl);
        $this->assertGreaterThan(
                0, $this->search_provider->parse($plugin, $data), "No hay resultados"
        );
    }

}
