<?php
require_once dirname(__FILE__) . '\..\..\..\..\..\vendor\autoload.php';
require_once dirname(__FILE__) . '\..\..\..\..\..\SynDsEsTorrent\modules\divxatope\host\host.php';

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-06-08 at 02:27:12.
 */
class SynoFileHostingDivxatopeTest extends \SynDsEsTorrent\utils\BaseHostTest {

    protected function setUp() {
        parent::setObject(new SynoFileHostingDivxatope("http://www.divxatope.com/descargar_torrent_374181-id_malefica_bluray_rip_ac3_5.1_espanol_castellano_2014.html", null, null, null));
    }
   
    /**
     * @covers SynoFileHostingNewPct::GetDownloadInfo
     */
    public function testGetDownloadInfo(){
        parent::GetDownloadInfo();
    }
}
