<?php
require_once dirname(__FILE__) . '\..\..\..\..\..\vendor\autoload.php';
require_once dirname(__FILE__) . '\..\..\..\..\..\SynDsEsTorrent\modules\newPct\host\host.php';

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-06-08 at 02:27:12.
 */
class SynoFileHostingNewPctTest extends \SynDsEsTorrent\utils\BaseHostTest {

    protected function setUp() {
        parent::setObject(new SynoFileHostingNewPct("http://www.newpct1.com/serie/aguila-roja/capitulo-601/hdtv-720p-ac3-5-1/", null, null, null));
    }
   
    /**
     * @covers SynoFileHostingNewPct::GetDownloadInfo
     */
    public function testGetDownloadInfo(){
        parent::GetDownloadInfo();
    }
}
