<?php

require_once dirname(__FILE__) . '\..\..\..\newPct\host\host.php';
// Constants required by host.php
define('LOGIN_FAIL', 1);
define('USER_IS_FREE', 2);
define('DOWNLOAD_STATION_USER_AGENT', "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.1916.114 Safari/537.36");
define('DOWNLOAD_URL', "dl");
define('DOWNLOAD_COOKIE', "coo");

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-06-08 at 02:27:12.
 */
class SynoFileHostingNewPctTest extends PHPUnit_Framework_TestCase {

    /**
     * @var SynoFileHostingNewPct
     */
    protected $object;
    protected $curl;
    
    const USUARIO = 'luskaner';
    const CONTRASEÑA = 'akpereral';

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->curl = curl_init();
        curl_setopt($this->curl, CURLOPT_COOKIE, "language=es_ES");
        curl_setopt($this->curl, CURLOPT_FAILONERROR, 1);
        curl_setopt($this->curl, CURLOPT_FOLLOWLOCATION, 1);
        curl_setopt($this->curl, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($this->curl, CURLOPT_TIMEOUT, 20);
        curl_setopt($this->curl, CURLOPT_USERAGENT, DOWNLOAD_STATION_USER_AGENT);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers SynoFileHostingNewPct::Verify
     */
//    public function testVerifyUserCorrect() {
//        $this->host = new SynoFileHostingNewPct(null, self::USUARIO, self::CONTRASEÑA, null);
//        $this->assertEquals($this->host->Verify(TRUE), USER_IS_FREE, "No se ha podido iniciar sesión con unas credenciales correctas");
//    }
    
    /**
     * @covers SynoFileHostingNewPct::GetDownloadInfo
     */
    public function testGetDownloadInfoFromSearch() {
        $this->checkDownloadisTorrent("http://www.tumejorjuego.com/descargar/index.php?link=descargar/torrent/57913/el-heredero-del-diablo-bluray-rip-ac3-51-espanol-castellano-2014.html");
    }
    
    /**
     * @covers SynoFileHostingNewPct::GetDownloadInfo
     */
    public function testGetDownloadInfoFromRss() {
        $this->checkDownloadisTorrent("http://www.newpct1.com/serie/drop-dead-diva/capitulo-511/");
    }   
    
    private function checkDownloadisTorrent($url){
        $this->host = new SynoFileHostingNewPct($url, self::USUARIO, self::CONTRASEÑA, null);
        $dlInfo = $this->host->GetDownloadInfo();
        curl_setopt($this->curl, CURLOPT_COOKIEFILE, $dlInfo[DOWNLOAD_COOKIE]);
        curl_setopt($this->curl, CURLOPT_URL, $dlInfo[DOWNLOAD_URL]);
        curl_exec($this->curl);
        $info = curl_getinfo($this->curl);
        $this->assertEquals($info["content_type"], "application/x-bittorrent", "El fichero a descargar no es un torrent, sino un '" . $info["content_type"]. "'");
    }
}
