<?php
require_once dirname(__FILE__) . '\..\..\..\..\..\vendor\autoload.php';
require_once dirname(__FILE__) . '\..\..\..\..\..\SynDsEsTorrent\modules\eliteTorrentNet\host\host.php';

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-06-08 at 02:27:12.
 */
class SynoFileHostingEliteTorrentNetTest extends \SynDsEsTorrent\utils\BaseHostTest
{
    protected function setUp()
    {
        parent::setObject(new SynoFileHostingEliteTorrentNet("http://www.elitetorrent.net/torrent/24737/the-listener-5x04", null, null, null));
    }

    /**
     * @covers SynoFileHostingEliteTorrentNet::GetDownloadInfo
     */
    public function testGetDownloadInfo()
    {
        parent::GetDownloadInfo();
    }
}
