<?php
namespace SynDsEsTorrent\utils;

require_once dirname(__FILE__) . '/../../../../modules/newPct/host/host.php';

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-06-08 at 02:27:12.
 */
class SynoFileHostingNewPctTest extends PHPUnit_Framework_TestCase {

    /**
     * @var SynoFileHostingNewPct
     */
    protected $object;
    protected $curl;
    
    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->curl = curl_init();
        curl_setopt($this->curl, CURLOPT_COOKIE, "language=es_ES");
        curl_setopt($this->curl, CURLOPT_FAILONERROR, 1);
        curl_setopt($this->curl, CURLOPT_FOLLOWLOCATION, 1);
        curl_setopt($this->curl, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($this->curl, CURLOPT_TIMEOUT, 20);
        curl_setopt($this->curl, CURLOPT_USERAGENT, DOWNLOAD_STATION_USER_AGENT);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }
   
    /**
     * @covers SynoFileHostingNewPct::GetDownloadInfo
     */
    public function testDownloadisTorrent(){
        $this->host = new SynoFileHostingNewPct("http://www.newpct1.com/serie/true-blood/capitulo-703/hdtv-720p-ac3-5-1/", null, null, null);
        $dlInfo = $this->host->GetDownloadInfo();
        curl_setopt($this->curl, CURLOPT_COOKIEFILE, $dlInfo[DOWNLOAD_COOKIE]);
        curl_setopt($this->curl, CURLOPT_URL, $dlInfo[DOWNLOAD_URL]);        
        curl_exec($this->curl);
        $info = curl_getinfo($this->curl);
        $this->assertEquals($info["content_type"], "application/x-bittorrent", "El fichero a descargar no es un torrent, sino un '" . $info["content_type"]. "'");
    }
}
