<?php
require_once dirname(__FILE__) . '\..\..\..\..\..\vendor\autoload.php';
require_once dirname(__FILE__) . '\..\..\..\..\..\SynDsEsTorrent\modules\newPct-newPct1\host\host.php';

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-06-08 at 02:27:12.
 */
class SynoFileHostingNewPctTest extends \SynDsEsTorrent\utils\BaseHostTest {

    /**
     * @covers SynoFileHostingNewPct::GetDownloadInfo
     */
    public function testGetDownloadInfo(){
        parent::setObject(new SynoFileHostingNewPct("http://www.newpct.com/descargar-serie/cougar-town/capitulo-501/", null, null, null));
        parent::GetDownloadInfo();
    }
    
    /**
     * @covers SynoFileHostingNewPct::GetDownloadInfo
     */
     public function testGetDownloadInfoNewPct1(){
        parent::setObject(new SynoFileHostingNewPct("http://www.newpct1.com/pelicula/las-aventuras-de-peabody-y-sherman//dlm/", null, null, null));
        parent::GetDownloadInfo();
    }
}
