<?php
require_once dirname(__FILE__) . '\..\..\..\..\..\vendor\autoload.php';
require_once dirname(__FILE__) . '\..\..\..\..\..\SynDsEsTorrent\modules\divxtotal\host\host.php';

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-06-08 at 02:27:12.
 */
class SynoFileHostingDivxTotalTest extends \SynDsEsTorrent\utils\BaseHostTest
{
    protected function setUp()
    {
        parent::setObject(new SynoFileHostingDivxTotal("http://www.divxtotal.com/musica/torrent/44391/va-verano-latino-total-2014/", null, null, null));
    }

    /**
     * @covers SynoFileHostingNewPct::GetDownloadInfo
     */
    public function testGetDownloadInfo()
    {
        parent::GetDownloadInfo();
    }
}
