<?php
require_once dirname(__FILE__) . '\..\..\..\..\..\vendor\autoload.php';
require_once dirname(__FILE__) . '\..\..\..\..\..\SynDsEsTorrent\modules\animeIndexOrg\host\host.php';

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-06-08 at 02:27:12.
 */
class SynoFileHostingAnimeIndexTest extends \SynDsEsTorrent\utils\BaseHostTest
{
    protected function setUp()
    {
        parent::setObject(new SynoFileHostingAnimeIndex("http://tracker.anime-index.org/index.php?page=torrent-details&id=379e17f0dae4b50b6347c707c6e0461755274fe6", null, null, null));
    }

    /**
     * @covers SynoFileHostingAnimeIndex::GetDownloadInfo
     */
    public function testGetDownloadInfo()
    {
        parent::GetDownloadInfo();
    }
}
