<?php

/*
    This file is part of SynDsEsTorrent.

    SynDsEsTorrent is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    SynDsEsTorrent is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with SynDsEsTorrent.  If not, see <http://www.gnu.org/licenses/>.
 */

namespace tests\modules\newPct_newPct1\host;

use modules\newpct_newPct1\host\SynoFileHostingNewPct;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-06-08 at 02:27:12.
 */
class SynoFileHostingNewPctTest extends \utils\BaseHostTest
{
    /**
     * @covers modules\newpct_newPct1\host\SynoFileHostingNewPct::GetDownloadInfo
     */
    public function testGetDownloadInfo()
    {
        parent::setObject(
            new SynoFileHostingNewPct(
                "http://www.newpct.com/descargar-serie/cougar-town/capitulo-501/"
            )
        );
        parent::getDownloadInfo();
    }

    /**
     * @covers modules\newpct_newPct1\host\SynoFileHostingNewPct::GetDownloadInfo
     */
    public function testGetDownloadInfoNewPct1()
    {
        parent::setObject(
            new SynoFileHostingNewPct(
                "http://www.newpct1.com/pelicula/las-aventuras-de-peabody-y-sherman//dlm/"
            )
        );
        parent::getDownloadInfo();
    }

    /**
     * @covers modules\newpct_newPct1\host\SynoFileHostingNewPct::__construct
     */
    public function testLoadInfo()
    {
        parent::setObject(
            new SynoFileHostingNewPct(
                "http://www.newpct.com/descargar-serie/cougar-town/capitulo-501/"
            )
        );
        parent::loadInfoTest();
    }
}
