<?php
require_once '..\modules\divxtotal\host\SynoFileHostingDivxTotal.php';
define('LOGIN_FAIL', 1);
define('USER_IS_FREE', 2);
define('DOWNLOAD_STATION_USER_AGENT', "Mozilla/5.0 (Windows NT 6.3; WOW64) Appl"
        . "eWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.1916.114 Safari/537.3"
        . "6");
define('DOWNLOAD_URL', "dl");
define('DOWNLOAD_COOKIE', "coo");

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-07-25 at 21:34:50.
 */
class SynoFileHostingDivxTotalTest extends PHPUnit_Framework_TestCase
{

    /**
     * @var SynoFileHostingDivxTotal
     */
    protected $host_provider;

    /**
     * @covers SynoFileHostingDivxTotal::GetDownloadInfo
     */
    public function testGetDownloadInfoNoNeed()
    {
        $this->host_provider = new SynoFileHostingDivxTotal(
                'http://www.divxtotal.com/download.php?id=43374',
                null, 
                null, 
                null
        );
        
        $dl_info = $this->host_provider->GetDownloadInfo();
        $this->assertEquals(
                $dl_info[DOWNLOAD_URL],
                'http://www.divxtotal.com/download.php?id=43374',
                "No tuvo que haber cambiado la url a ${dl_info[DOWNLOAD_URL]}"
        );
    }
    
    /**
     * @covers SynoFileHostingDivxTotal::GetDownloadInfo
     */
    public function testGetDownloadInfoSerie()
    {
        $this->host_provider = new SynoFileHostingDivxTotal(
                'http://www.divxtotal.com/series/orange-is-the-new-black-652/?cap=Orange%20Is%20The%20New%20Black%202x06',
                null, 
                null, 
                null
        );
        
        $dl_info = $this->host_provider->GetDownloadInfo();
        $res_url = $this->regexp('(?<url>.*.torrent)$', $dl_info[DOWNLOAD_URL]);
        $this->assertArrayHasKey(
                'url',
                $res_url,
                "No pudo obtener la url"
        );
    }
    
    
    /**
     * @covers SynoFileHostingDivxTotal::GetDownloadInfo
     */
    public function testGetDownloadInfoRss()
    {
         $this->host_provider = new SynoFileHostingDivxTotal(
                'http://www.divxtotal.com/musica/torrent/43890/va-temazos-para-'
                 . 'tus-fiestas-vol-13/',
                null, 
                null, 
                null
        );
        
        $dl_info = $this->host_provider->GetDownloadInfo();
        $this->assertEquals(
                $dl_info[DOWNLOAD_URL],
                'http://www.divxtotal.com/download.php?id=43890',
                "No tuvo que haber cambiado la url a ${dl_info[DOWNLOAD_URL]}"
        );
    }
    
    private function regexp($regexp, $texto, $global = false)
    {
        $res = array();
        if ($global) {
            if (preg_match_all("/$regexp/siU", $texto, $res, PREG_SET_ORDER)) {
                return $res;
            } else {
                return '';
            }
        } else {
            if (preg_match("/$regexp/siU", $texto, $res)) {
                return $res;
            } else {
                return '';
            }
        }
    }

}
